#!/bin/bash

#This is how to completely build an Ubuntu Server by combining multiple hard drives into a single LVM, adding Wordpress for content direction, adding Plex for content viewing, Samba to add content, Retroarch Web Player for vintage console games, and using Amp to install games servers
# Don't forget to properly format your hard drives prior to installing them


#Server: akmedia, User: rickover, PW: integrity1

sudo apt-get update

sudo apt-get upgrade -y

#Remove snap because we already have apt and it messes up the drive allocations https://techwiser.com/remove-snap-ubuntu/

sudo snap list

# Clear the snap cache

sudo rm -rf /var/cache/snapd/

#Uninstall snap and the GUI

sudo apt autoremove --purge snapd gnome-software-plugin-snap -y

#Clear snap preferences

rm -fr ~/snap

#Put snap on hold
sudo apt-mark hold snapd

#Update the logind.conf file so closing the lid does not stop anything

sudo nano /etc/systemd/logind.conf

# Update the line "HandleLidSwitch=suspend" to "HandleLidSwitch=ignore"
# Verify the line "HandleLidSwitchDocked=ignore"

#Then restart the service
sudo systemctl restart systemd-logind

# Installing Apache https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-20-04



sudo apt update

sudo apt install apache2
sudo ufw app list
sudo ufw allow in "Apache"
sudo ufw status

#View Test page to ensure it works
http://your_server_ip

# Installing mysql
sudo apt install mysql-server
sudo mysql_secure_installation
#Password Validation - Select NO
#Validate it installed
sudo mysql 
mysql> exit
sudo apt install php libapache2-mod-php php-mysql
#Check Version
php -v






